---
# tasks file for percona-server
- name: create (lock) directory
  file:
    path: /var/lib/ansible/percona-server/lock
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: [configuration, percona-server, percona-server-toolkit-udfs]

- name: install toolkit UDF's
  shell: "mysql -e \"DROP FUNCTION IF EXISTS {{ item.function }}; CREATE FUNCTION {{ item.function }} RETURNS INTEGER SONAME '{{ item.soname }}'\" && touch /var/lib/ansible/percona-server/lock/{{ item.soname }}"
  args:
    creates: "/var/lib/ansible/percona-server/lock/{{ item.soname }}"
  with_items:
  - function: fnv1a_64
    soname: libfnv1a_udf.so
  - function: fnv_64
    soname: libfnv_udf.so
  - function: murmur_hash
    soname: libmurmur_udf.so
  tags: [configuration, percona-server, percona-server-toolkit-udfs]

- name: create (specified) database
  mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    state: present
  with_items: percona_server_databases_present
  when: percona_server_databases_present
  tags: [configuration, percona-server, percona-server-create-databases]

- name: remove (specified) database
  mysql_db:
    name: "{{ item.name }}"
    state: absent
  with_items: percona_server_databases_absent
  when: percona_server_databases_absent
  tags: [configuration, percona-server, percona-server-remove-databases]

- name: create (specified) users
  mysql_user:
    name: "{{ item[0].name }}"
    password: "{{ item[0].password }}"
    priv: "{{ item[0].priv | join('/') }}"
    host: "{{ item[1] }}"
    state: present
  with_nested:
    - percona_server_users_present
    - percona_server_users_present_4_hosts
  when: percona_server_users_present and percona_server_users_present_4_hosts
  tags: [configuration, percona-server, percona-server-create-users]

- name: remove (specified) users
  mysql_user:
    name: "{{ item[0].name }}"
    host: "{{ item[1] }}"
    state: absent
  with_nested:
    - percona_server_users_absent
    - percona_server_users_absent_4_hosts
  when: percona_server_users_absent and percona_server_users_absent_4_hosts
  tags: [configuration, percona-server, percona-server-remove-users]
