---
# tasks file for percona-server
- name: install toolkit UDF's
  shell: "mysql -e \"CREATE FUNCTION {{ item.function }} RETURNS INTEGER SONAME '{{ item.soname }}'\" && touch /var/log/mysql/{{ item.soname }}.created"
  args:
    creates: "/var/log/mysql/{{ item.soname }}.created"
  with_items:
  - function: fnv1a_64
    soname: libfnv1a_udf.so
  - function: fnv_64
    soname: libfnv_udf.so
  - function: murmur_hash
    soname: libmurmur_udf.so
  tags: [configuration, percona-server, percona-server-toolkit-udfs]

- name: create (specified) database
  mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    state: present
  with_items: percona_server_databases_present
  when: percona_server_databases_present
  tags: [configuration, percona-server, percona-server-create-databases]

- name: remove (specified) database
  mysql_db:
    name: "{{ item.name }}"
    state: absent
  with_items: percona_server_databases_absent
  when: percona_server_databases_absent
  tags: [configuration, percona-server, percona-server-remove-databases]

- name: create (specified) users
  mysql_user:
    name: "{{ item.name }}"
    state: present
  with_items: percona_server_users_present
  when: percona_server_users_present
  tags: [configuration, percona-server, percona-server-create-users]

- name: remove (specified) users
  mysql_user:
    name: "{{ item.name }}"
    state: absent
  with_items: percona_server_users_absent
  when: percona_server_users_absent
  tags: [configuration, percona-server, percona-server-remove-users]
