# tasks file for percona-server
---

- name: ib logfile | store datadir
  mysql_variables:
    variable: datadir
  register: datadir_value
  tags:
    - percona-server-store datadir

- name: ib logfile | stop service
  service:
    name: mysql
    state: stopped
  tags:
    - percona-server-ib-logfile-stop-service

- name: ib logfile | remove ib_logfile(s)
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ datadir_value.msg.0.1 }}ib_logfile0"
    - "{{ datadir_value.msg.0.1 }}ib_logfile1"
  tags:
    - percona-server-ib-logfile-remove

- name: ib logfile | start service
  service:
    name: mysql
    state: started
  tags:
    - percona-server-ib-logfile-start-service
