# tasks file for percona-server
---
- name: install | configure debconf
  debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items: "{{ percona_server_debconf_selections }}"
  changed_when: false
  tags:
    - percona-server-install-configure-debconf

- name: install | dependencies
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
  with_items: "{{ percona_server_dependencies }}"
  tags:
    - percona-server-install-dependencies

- block:
  - name: install | service | stop
    service:
      name: mysql
      state: stopped

  - name: install | service | cleanup
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /etc/mysql/percona-server.conf.d/mysqld_safe.cnf
      - /etc/mysql/percona-server.conf.d/mysqld.cnf
      - /etc/mysql/percona-server.cnf

  when: mysqld_installed.rc != 0

- name: install | dependencies | check service
  service:
    name: mysql
    state: started
  tags:
    - percona-server-install-dependencies
    - percona-server-install-dependencies-check

- name: install | additional
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
  with_items: "{{ percona_server_install }}"
  tags:
    - percona-server-install-additional
