# tasks file for percona-server
---
- name: install | configure debconf
  debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items: "{{ percona_server_debconf_selections }}"
  changed_when: false
  tags:
    - percona-server-install-configure-debconf

- name: install | packages
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: yes
  with_items: "{{ percona_server_packages }}"
  tags:
    - percona-server-install-packages
