# tasks file for percona-server, queries
---
- name: queries | execute sql
  command: "mysql --database=\"{{ item.0.database }}\" -e \"{{ item.1 }}; SELECT ROW_COUNT();\" --skip-column-names"
  register: rows_affected
  changed_when: "rows_affected.stdout_lines[-1] | int > 0"
  with_subelements:
    - percona_server_queries
    - queries
  tags:
    - percona-server-execute-sql
