# tasks file for percona-server
---

- name: repository | install | dependencies
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items:
    - dirmngr
  when: ansible_distribution == 'Debian' and ansible_distribution_version is version('9', '>=')
  tags:
    - percona-server-repository-install
    - percona-server-repository-install-dependencies

- name: repository | add
  apt:
    deb: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
  tags:
    - percona-server-repository-add
